//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WWhizNet.rc
//
#define IDS_WORKSPACEWHIZ_LONGNAME      1
#define IDS_WORKSPACEWHIZ_DESCRIPTION   2
#define IDS_CMD_STRING                  3
#define IDS_PREFDLG_CAPTION             3
#define IDS_PROJNAME                    100
#define IDR_ADDIN                       101
#define IDR_CONNECT                     102
#define IDR_TOOLBAR_MEDIUM              128
#define IDR_TOOLBAR_LARGE               129
#define IDD_ABOUTBOX                    130
#define IDD_FINDFILE                    131
#define IDR_TOOLBAR_MEDIUM1             132
#define IDD_EXTRAFILES                  132
#define IDD_PREFERENCES                 133
#define IDD_FINDTAG                     134
#define IDD_FT_PREFERENCES              135
#define IDD_STATUS                      136
#define IDM_FINDFILEPOPUP               136
#define IDD_TEMPLATESELECT              137
#define IDM_FINDTAG_POPUP               137
#define IDD_TEMPLATEFILELIST            138
#define IDD_TEMPLATEWIZARD              139
#define IDD_PREF_KEYBINDINGS            140
#define IDD_PREF_KEYBINDINGS2           141
#define IDD_PREF_KEYBINDINGS3           142
#define IDD_PREF_HEADERFLIP             143
#define IDD_PREF_CTAGS                  144
#define IDD_HISTORY                     145
#define IDD_PREF_SKINS                  146
#define IDR_AB_HTML                     147
#define IDD_AUTOCOMPLETETAG             149
#define IDI_WWHIZ                       151
#define IDB_CI_WWOPTIONS                179
#define IDB_CI_WWFILEOPEN               180
#define IDB_CI_WWFILEGLOBALOPEN         181
#define IDB_CI_WWHEADERFLIP             182
#define IDB_CI_WWFILEFINDPREV           183
#define IDB_CI_WWFILEFINDNEXT           184
#define IDB_CI_WWHISTORYBACK            185
#define IDB_CI_WWHISTORYFORWARD         186
#define IDB_CI_WWHISTORYDLG             187
#define IDB_CI_WWTAGFINDDLG             188
#define IDB_CI_WWTAGFINDSPECIALDLG      189
#define IDB_CI_WWTAGFLIP                190
#define IDB_CI_WWTAGFINDATCURSOR        191
#define IDB_CI_WWTAGFINDATCURSORDLG     192
#define IDB_CI_WWTAGFINDPREV            193
#define IDB_CI_WWTAGFINDNEXT            194
#define IDB_CI_WWTAGCOMPLETEPREV        195
#define IDB_CI_WWTAGCOMPLETENEXT        196
#define IDB_CI_WWTAGCOMPLETERESTORE     197
#define IDB_CI_WWTAGCOMPLETEDLG         198
#define IDB_CI_WWTEMPLATESELECT         199
#define IDB_CI_WWTEMPLATECOMPLETE       200
#define IDC_COM_ABOUT                   1000
#define IDC_COM_EXTRAFILES              1001
#define IDC_COM_CURRENTFILE             1003
#define IDC_FF_FILES                    1020
#define IDC_FF_FILENAME                 1021
#define IDC_FF_REFRESH                  1022
#define IDC_FF_SCOPE                    1023
#define IDC_FF_SCOPE_PROJECT            1024
#define IDC_FF_SCOPE_WORKSPACE          1025
#define IDC_FF_SCOPE_GLOBAL             1026
#define IDC_SCOPE_GLOBAL                1026
#define IDC_FF_PREFIX                   1027
#define IDC_EP_LIST                     1040
#define IDC_EP_ADD                      1041
#define IDC_EP_REMOVE                   1042
#define IDC_EP_FILENAME                 1043
#define IDC_EP_BROWSE                   1044
#define IDC_FT_TAGS                     1050
#define IDC_FT_PARENT                   1051
#define IDC_FT_NAME                     1052
#define IDC_FT_REBUILDTAGS              1053
#define IDC_FT_SCOPE                    1054
#define IDC_FT_SCOPE_FILE               1055
#define IDC_FT_SCOPE_PROJECT            1056
#define IDC_FT_SCOPE_WORKSPACE          1057
#define IDC_FT_INFO_FILENAME            1058
#define IDC_FT_INFO_SEARCHSTRING        1059
#define IDC_FT_INFO_FRAME               1060
#define IDC_FT_SHOW                     1061
#define IDC_FT_TYPECOMBO                1062
#define IDC_FT_REFRESHTAGS              1063
#define IDC_FT_INFO_MISC                1064
#define IDC_ST_LIST                     1069
#define IDC_AB_REGISTER                 1070
#define IDC_TS_TREE                     1080
#define IDC_TS_FILELIST                 1081
#define IDC_TS_DESCRIPTION              1082
#define IDC_TS_MEMO                     1083
#define IDC_TFL_LIST                    1090
#define IDC_TFL_ADD                     1091
#define IDC_TFL_REMOVE                  1092
#define IDC_TFL_EDIT                    1093
#define IDC_TW_NEXT                     1100
#define IDC_TW_PREVIOUS                 1101
#define IDC_TW_HTML                     1102
#define IDC_H_RESET                     1110
#define IDC_H_FILES                     1111
#define IDC_PKB_KEYCHECK1               1200
#define IDC_PKB_KEYCHECK2               1201
#define IDC_PKB_KEYCHECK3               1202
#define IDC_PKB_KEYCHECK4               1203
#define IDC_PKB_KEYCHECK5               1204
#define IDC_PKB_KEYCHECK6               1205
#define IDC_PKB_KEYCHECK7               1206
#define IDC_PKB_KEYCHECK8               1207
#define IDC_PKB_KEYCHECK9               1208
#define IDC_PKB_KEYCHECK10              1209
#define IDC_PKB_KEYCHECK11              1210
#define IDC_PKB_KEYCHECK12              1211
#define IDC_PKB_KEYCHECK13              1212
#define IDC_PKB_KEYCHECK14              1213
#define IDC_PKB_KEYCHECK15              1214
#define IDC_PKB_KEYCHECK16              1215
#define IDC_PKB_KEYCHECK17              1216
#define IDC_PKB_KEYCHECK18              1217
#define IDC_PKB_KEYCHECK19              1218
#define IDC_PKB_KEYCHECK20              1219
#define IDC_PKB_KEYCHECK21              1220
#define IDC_PKB_KEY1                    1230
#define IDC_PKB_KEY2                    1231
#define IDC_PKB_KEY3                    1232
#define IDC_PKB_KEY4                    1233
#define IDC_PKB_KEY5                    1234
#define IDC_PKB_KEY6                    1235
#define IDC_PKB_KEY7                    1236
#define IDC_PKB_KEY8                    1237
#define IDC_PKB_KEY9                    1238
#define IDC_PKB_KEY10                   1239
#define IDC_PKB_KEY11                   1240
#define IDC_PKB_KEY12                   1241
#define IDC_PKB_KEY13                   1242
#define IDC_PKB_KEY14                   1243
#define IDC_PKB_KEY15                   1244
#define IDC_PKB_KEY16                   1245
#define IDC_PKB_KEY17                   1246
#define IDC_PKB_KEY18                   1247
#define IDC_PKB_KEY19                   1248
#define IDC_PKB_KEY20                   1249
#define IDC_PKB_KEY21                   1250
#define IDC_PKB_ASSIGN                  1260
#define IDC_PKB_RESET                   1261
#define IDC_PKB_ASSIGNALLPAGES          1262
#define IDC_PHF_EXTLIST                 1270
#define IDC_PHF_EXTEDIT                 1271
#define IDC_PHF_ADD                     1272
#define IDC_PHF_REMOVE                  1273
#define IDC_PHF_RESET                   1274
#define IDC_PC_EXTEDIT                  1280
#define IDC_PC_ADD                      1281
#define IDC_PC_REMOVE                   1282
#define IDC_PC_RESET                    1283
#define IDC_PC_EXTLIST                  1284
#define IDC_PC_AUTOSAVECHANGES          1285
#define IDC_PC_AUTOPACKCHANGES          1286
#define IDC_PC_USETAGCURSORDIALOG       1287
#define IDC_PC_AUTOREFRESHTAGS          1288
#define IDC_PC_AUTOSAVEALL              1289
#define IDC_PC_SCANFILESTASKSWITCH      1290
#define IDC_PC_TOKENEDIT                1291
#define IDC_PC_TOKENADD                 1292
#define IDC_PC_TOKENREMOVE              1293
#define IDC_PC_TOKENRESET               1294
#define IDC_AB_HTML                     1300
#define IDC_PC_TOKENLIST                1310
#define IDC_EP_NEVERREFRESH             1312
#define IDS_MISSINGTOOLBARCONTENTS      9000
#define IDS_CI_WWOPTIONS                9999
#define IDS_CI_WWFILEOPEN               10000
#define IDS_CI_WWFILEGLOBALOPEN         10001
#define IDS_CI_WWHEADERFLIP             10002
#define IDS_CI_WWFILEFINDPREV           10003
#define IDS_CI_WWFILEFINDNEXT           10004
#define IDS_CI_WWHISTORYBACK            10005
#define IDS_CI_WWHISTORYFORWARD         10006
#define IDS_CI_WWHISTORYDLG             10007
#define IDS_CI_WWTAGFINDDLG             10008
#define IDS_CI_WWTAGFINDSPECIALDLG      10009
#define IDS_CI_WWTAGFLIP                10010
#define IDS_CI_WWTAGFINDATCURSOR        10011
#define IDS_CI_WWTAGFINDATCURSORDLG     10012
#define IDS_CI_WWTAGFINDPREV            10013
#define IDS_CI_WWTAGFINDNEXT            10014
#define IDS_CI_WWTAGCOMPLETEPREV        10015
#define IDS_CI_WWTAGCOMPLETENEXT        10016
#define IDS_CI_WWTAGCOMPLETERESTORE     10017
#define IDS_CI_WWTAGCOMPLETEDLG         10018
#define IDS_CI_WWTEMPLATESELECT         10019
#define IDS_CI_WWTEMPLATECOMPLETE       10020
#define IDS_CI_WWPASTEFIX               10021
#define IDC_FTP_GOTOTAGDEFINITION       32772
#define IDC_FTP_GOTOTAGDECLARATION      32773
#define IDC_FTP_COPYTAG                 32774
#define IDC_FTP_COPYPARENT              32775
#define IDC_FFP_COPYPATHTOCLIPBOARD     32776
#define IDC_FFP_COPYFULLPATHTOCLIPBOARD 32777
#define IDC_FFP_SELECT                  45000
#define IDC_FFP_HEADERFLIP              45001
#define IDC_FFP_OPENASTEXT              45002
#define IDC_FFP_READONLY                45003
#define IDC_FFP_PROPERTIES              45004
#define ID_DUMMY_FILESYSTEM_UNAVAILABLE 45005
#define IDC_FFP_EXPLORE                 45006

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1318
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
